firsttune/urls.py
from . import views
from django.urls import path
from django.views.generic.edit import CreateView


app_name = 'firsttune'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post1', views.Post1View.as_view(), name='post1'),
    path('education', views.EducationView.as_view(), name='education'),
    path('information', views.InformationView.as_view(), name='information'),
    path('africa', views.AfricaView.as_view(), name='africa'),
    path('about', views.AboutView.as_view(), name='about'),

    # path('featured/', views.FeaturedView.as_view(), name='featured'),
    # path('team/', views.TeamView.as_view(), name='team'),
    # path('contact/', views.ContactView.as_view(), name='contact'),



    

    
]

patstune/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firsttune.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

firsttune/models.py
from django.db import models

# Create your models here.

firsttune/views.py
# Create your views here.
from django.shortcuts import render
from typing import FrozenSet
from django import template
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db.models.query import QuerySet
from django.forms.models import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render, redirect, resolve_url
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect, request
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import CreateView, FormView, UpdateView
from django.views.generic.list import ListView
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.conf import settings 
# from bootstrap_datepicker_plus import DatePickerInput
from django.core.mail import send_mail
from django.views.generic import TemplateView

# Create your views here.



class IndexView(TemplateView):
    template_name = "firsttune/index.html"
    

class Post1View(TemplateView):
    template_name = "firsttune/post1.html"

class EducationView(TemplateView):
    template_name = "firsttune/education.html"

class InformationView(TemplateView):
    template_name = "firsttune/information.html"

class AfricaView(TemplateView):
    template_name = "firsttune/africa.html"

class AboutView(TemplateView):
    template_name = "firsttune/about.html"


# class TeamView(TemplateView):
#     template_name = 'michael/team.html'

# class ContactView(TemplateView):
#     template_name = 'michael/contact.html'

firsttune/templates/firsttune/africa.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'firsttune/index.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link rel="stylesheet" href="{% static 'michael/animate.css' %}"> -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    <script src="jquery-3.6.0.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'firsttune/index.js' %}"></script>
    <link rel="stylesheet" href="{% static 'firsttune/animate.css' %}">


    <title>patstune</title>
</head>

<body class="body">
    <div id='homepic' class=" container-fluid homepic align-items-center justify-content-center">
        <div id='homerow' class="row align-items-center justify-content-center">
            <div class="col-sm-12 text-center">
                <h1 class="font-weight-bold text-large font-large text-white 
                hometext customfont px-5 px-sm-0 animate__animated animate__fadeIn animate__slower">PAT'S TUNE</h1>
            </div>
            <div class="col-sm-12 text-center">
                <p class="text-capitalize font-weight-bold text-large font-large text-white 
                  px-5 px-sm-0 animate__animated animate__fadeIn 
                animate__slower">Rich Information for this generation</p>
            </div>
        </div>
    </div>
    <div class='wait_small' id='wait_small'>

        <div class="container-fluid box_shadow animate__animated animate__fadeIn animate__slow position-relative">
            <div class="row align-items-center justify-content-center brandcolor_border">
                <nav class="navbar navbar-expand-lg fixed navbar-light w-100 brandcolor"
                    style="background-color: inherit; ">
                    <a class="navbar-brand  " style="">
                        <!-- <img src="{% static 'michael/clipmask2.jpg' %}" class="nav-image" height="35px" width="35px"></img> -->
                        <span class="customfont text-dark"> PATSTUNE</span>
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse  " id="navbarNav">

                        <ul class="nav navbar-nav navbar-right ml-auto">

                            <li class="nav-text active navbar-right">
                                <a href="{% url 'firsttune:index' %}" class="nav-link nav_link_ text-dark" style=" font-weight: 350;">Home</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'firsttune:education' %}" class="nav-link nav_link_ text-dark" style="font-weight: 350;">Education</a>
                            </li>
                            <li class="nav-text active  float-right">
                                <a href="{% url 'firsttune:information' %}" class="nav-link nav_link_ text-dark" style=" font-weight: 350;">Information <span
                                        class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-text active navbar-right">
                                <a href="{% url 'firsttune:africa' %}" class="nav-link nav_link_ text-dark" style=" font-weight: 350;">Africa</a>
                            </li>
                            <li class="nav-text active navbar-right">
                                <a href="{% url 'firsttune:about' %}" class="nav-link nav_link_ text-dark" style=" font-weight: 350;">About</a>
                            </li>

                        </ul>
                    </div>

                </nav>
                
            </div>
            <div class="row align-items-end justify-content-end position-absolute socials">
                <div class="col-sm- ">
                    <a href="#" class="fa fa-facebook"></a>
                    <a href="#" class="fa fa-twitter"></a>


                </div>
            </div>

        </div>
        {% block content1 %}

        <div class="container bg-white py-5 mt-2 animate__animated animate__fadeIn animate__slower ">
            <div class="row align-items-end justify-content-start justify-content-md-start 
             my-2 border_dark_ mb-4 mx-3 mx-sm-auto">
                
                <div class="col-sm- mr-0 mr-md-5 mb-4 mb-md-0">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                            <h6>Newest Articles</h6>
                        <div class="">
                            <img src="{% static 'firsttune/p7.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article One: What is ?</p>

                        </div>
                    </a>


                </div>
                <div class="col-sm- mr-0 mr-md-5 mb-4 mb-md-0">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                        <div class="">
                            <img src="{% static 'firsttune/p8.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article Two: What is Life?</p>

                        </div>
                    </a>


                </div>
            </div>
            <div class="row align-items-end justify-content-start justify-content-md-start
             my-5 border_dark_ mb-4 mx-3 mx-sm-auto">
                <div class="col-sm- mr-0 mr-md-5 mb-4 mb-md-0">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                        <div class="">
                            <img src="{% static 'firsttune/p9.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article 3: What is Life?</p>

                        </div>
                    </a>


                </div>
                <div class="col-sm- mr-0 mr-md-5 mb-4 mb-md-0">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                        <div class="">
                            <img src="{% static 'firsttune/p7.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article 4: What is Life?</p>

                        </div>
                    </a>


                </div>
                <div class="col-sm- mr-0 mr-md-5 mb-4 mb-md-0">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                        <div class="">
                            <img src="{% static 'firsttune/p8.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article 5: What is Life?</p>


                        </div>
                    </a>


                </div>
            </div>
            <div class="row align-items-center justify-content-start justify-content-md-start my-2 
            pt-2 border_dark_ mb-4 mx-3 mx-sm-auto">
                <div class="col-sm- mb-4 mb-md-0 ">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                        <div class="">
                            <img src="{% static 'firsttune/p9.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article 6: What is Life?</p>

                        </div>
                    </a>


                </div>
            </div>


            {% endblock %}
        </div>
</body>

</html>

firsttune/templates/firsttune/education.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'firsttune/index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'firsttune/educational.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link rel="stylesheet" href="{% static 'michael/animate.css' %}"> -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    <script src="jquery-3.6.0.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'firsttune/index.js' %}"></script>
    <link rel="stylesheet" href="{% static 'firsttune/animate.css' %}">


    <title>patstune</title>
</head>

<body class="body">
    <div id='homepic' class=" container-fluid homepic align-items-center justify-content-center">
        <div id='homerow' class="row align-items-center justify-content-center">
            <div class="col-sm-12 text-center">
                <h1 class="font-weight-bold text-large font-large text-white 
                hometext customfont px-5 px-sm-0 animate__animated animate__fadeIn animate__slower">PAT'S TUNE</h1>
            </div>
            <div class="col-sm-12 text-center">
                <p class="text-capitalize font-weight-bold text-large font-large text-white 
                  px-5 px-sm-0 animate__animated animate__fadeIn 
                animate__slower">Rich Information for this generation</p>
            </div>
        </div>
    </div>
    <div class='wait_small' id='wait_small'>

        <div class="container-fluid box_shadow animate__animated animate__fadeIn animate__slow position-relative">
            <div class="row align-items-center justify-content-center brandcolor_border">
                <nav class="navbar navbar-expand-lg fixed navbar-light w-100 brandcolor"
                    style="background-color: inherit; ">
                    <a class="navbar-brand  " style="">
                        <!-- <img src="{% static 'michael/clipmask2.jpg' %}" class="nav-image" height="35px" width="35px"></img> -->
                        <span class="customfont text-dark"> PATSTUNE</span>
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse  " id="navbarNav">

                        <ul class="nav navbar-nav navbar-right ml-auto">

                            <li class="nav-text active navbar-right">
                                <a href="{% url 'firsttune:index' %}" class="nav-link nav_link_ text-dark" style=" font-weight: 350;">Home</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'firsttune:education' %}" class="nav-link nav_link_ text-dark" style="font-weight: 350;">Education</a>
                            </li>
                            <li class="nav-text active  float-right">
                                <a href="{% url 'firsttune:information' %}" class="nav-link nav_link_ text-dark" style=" font-weight: 350;">Information <span
                                        class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-text active navbar-right">
                                <a href="{% url 'firsttune:africa' %}" class="nav-link nav_link_ text-dark" style=" font-weight: 350;">Africa</a>
                            </li>
                            <li class="nav-text active navbar-right">
                                <a href="{% url 'firsttune:about' %}" class="nav-link nav_link_ text-dark" style=" font-weight: 350;">About</a>
                            </li>

                        </ul>
                    </div>

                </nav>
                
            </div>
            <div class="row align-items-end justify-content-end position-absolute socials">
                <div class="col-sm- ">
                    <a href="#" class="fa fa-facebook"></a>
                    <a href="#" class="fa fa-twitter"></a>

                
                </div>
                
            </div>

        </div>
        {% block content1 %}

        <div class="container bg-white py-5 pt-0 animate__animated animate__fadeIn animate__slower ">
           
            <!-- <div class="row align-items-center justify-content-center educational_row">
                <div class="col-sm-4 ">
                    <img src="{% static 'firsttune/education1.png' %}" class="img-fluid  w-100">

                
                </div> 
                <div class="col-sm-4">
                    <h4>Educational Content For Everyone</h4>
                </div>
            </div>
            -->
            <div class="row align-items-center justify-content-center justify-content-sm-start">
                <div class="col-sm- text-center text-sm-left educational_row mb-5 w-100">
                    <img src="{% static 'firsttune/education1.png' %}" class="img-fluid ">
                    <h2 class='text-uppercase d-block  d-sm-inline '>Education</h2>
                </div>
                
            </div>
            <div class="row align-items-end justify-content-start justify-content-md-start 
             my-2 border_dark_ mb-4 mx-3 mx-sm-auto">
                
               
                <div class="col-sm- mr-0 mr-md-5 mb-4 mb-md-0 ">
                    
                    <a href="{% url 'firsttune:post1' %}" class="customcolor w-100">
                        
                        <div class="">
                            <img src="{% static 'firsttune/p7.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article One: What is ?</p>

                        </div>
                    </a>


                </div>
                <div class="col-sm- mr-0 mr-md-5 mb-4 mb-md-0">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                        <div class="">
                            <img src="{% static 'firsttune/p8.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article Two: What is Life?</p>

                        </div>
                    </a>


                </div>
            </div>
            <div class="row align-items-end justify-content-start justify-content-md-start
             my-5 border_dark_ mb-4 mx-3 mx-sm-auto">
                <div class="col-sm- mr-0 mr-md-5 mb-4 mb-md-0">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                        <div class="">
                            <img src="{% static 'firsttune/p9.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article 3: What is Life?</p>

                        </div>
                    </a>


                </div>
                <div class="col-sm- mr-0 mr-md-5 mb-4 mb-md-0">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                        <div class="">
                            <img src="{% static 'firsttune/p7.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article 4: What is Life?</p>

                        </div>
                    </a>


                </div>
                <div class="col-sm- mr-0 mr-md-5 mb-4 mb-md-0">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                        <div class="">
                            <img src="{% static 'firsttune/p8.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article 5: What is Life?</p>


                        </div>
                    </a>


                </div>
            </div>
            <div class="row align-items-center justify-content-start justify-content-md-start my-2 
            pt-2 border_dark_ mb-4 mx-3 mx-sm-auto">
                <div class="col-sm- mb-4 mb-md-0 ">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                        <div class="">
                            <img src="{% static 'firsttune/p9.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article 6: What is Life?</p>

                        </div>
                    </a>


                </div>
            </div>


            {% endblock %}
        </div>
</body>

</html>

firsttune/templates/firsttune/information.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'firsttune/index.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link rel="stylesheet" href="{% static 'michael/animate.css' %}"> -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    <script src="jquery-3.6.0.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'firsttune/index.js' %}"></script>
    <link rel="stylesheet" href="{% static 'firsttune/animate.css' %}">


    <title>patstune</title>
</head>

<body class="body">
    <div id='homepic' class=" container-fluid homepic align-items-center justify-content-center">
        <div id='homerow' class="row align-items-center justify-content-center">
            <div class="col-sm-12 text-center">
                <h1 class="font-weight-bold text-large font-large text-white 
                hometext customfont px-5 px-sm-0 animate__animated animate__fadeIn animate__slower">PAT'S TUNE</h1>
            </div>
            <div class="col-sm-12 text-center">
                <p class="text-capitalize font-weight-bold text-large font-large text-white 
                  px-5 px-sm-0 animate__animated animate__fadeIn 
                animate__slower">Rich Information for this generation</p>
            </div>
        </div>
    </div>
    <div class='wait_small' id='wait_small'>

        <div class="container-fluid box_shadow animate__animated animate__fadeIn animate__slow position-relative">
            <div class="row align-items-center justify-content-center brandcolor_border">
                <nav class="navbar navbar-expand-lg fixed navbar-light w-100 brandcolor"
                    style="background-color: inherit; ">
                    <a class="navbar-brand  " style="">
                        <!-- <img src="{% static 'michael/clipmask2.jpg' %}" class="nav-image" height="35px" width="35px"></img> -->
                        <span class="customfont text-dark"> PATSTUNE</span>
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse  " id="navbarNav">

                        <ul class="nav navbar-nav navbar-right ml-auto">

                            <li class="nav-text active navbar-right">
                                <a href="{% url 'firsttune:index' %}" class="nav-link nav_link_ text-dark" style=" font-weight: 350;">Home</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'firsttune:education' %}" class="nav-link nav_link_ text-dark" style="font-weight: 350;">Education</a>
                            </li>
                            <li class="nav-text active  float-right">
                                <a href="{% url 'firsttune:information' %}" class="nav-link nav_link_ text-dark" style=" font-weight: 350;">Information <span
                                        class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-text active navbar-right">
                                <a href="{% url 'firsttune:africa' %}" class="nav-link nav_link_ text-dark" style=" font-weight: 350;">Africa</a>
                            </li>
                            <li class="nav-text active navbar-right">
                                <a href="{% url 'firsttune:about' %}" class="nav-link nav_link_ text-dark" style=" font-weight: 350;">About</a>
                            </li>

                        </ul>
                    </div>

                </nav>
                
            </div>
            <div class="row align-items-end justify-content-end position-absolute socials">
                <div class="col-sm- ">
                    <a href="#" class="fa fa-facebook"></a>
                    <a href="#" class="fa fa-twitter"></a>


                </div>
            </div>

        </div>
        {% block content1 %}

        <div class="container bg-white py-5 mt-2 animate__animated animate__fadeIn animate__slower ">
            <div class="row align-items-end justify-content-start justify-content-md-start 
             my-2 border_dark_ mb-4 mx-3 mx-sm-auto">
                
                <div class="col-sm- mr-0 mr-md-5 mb-4 mb-md-0">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                            <h6>Newest Articles</h6>
                        <div class="">
                            <img src="{% static 'firsttune/p7.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article One: What is ?</p>

                        </div>
                    </a>


                </div>
                <div class="col-sm- mr-0 mr-md-5 mb-4 mb-md-0">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                        <div class="">
                            <img src="{% static 'firsttune/p8.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article Two: What is Life?</p>

                        </div>
                    </a>


                </div>
            </div>
            <div class="row align-items-end justify-content-start justify-content-md-start
             my-5 border_dark_ mb-4 mx-3 mx-sm-auto">
                <div class="col-sm- mr-0 mr-md-5 mb-4 mb-md-0">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                        <div class="">
                            <img src="{% static 'firsttune/p9.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article 3: What is Life?</p>

                        </div>
                    </a>


                </div>
                <div class="col-sm- mr-0 mr-md-5 mb-4 mb-md-0">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                        <div class="">
                            <img src="{% static 'firsttune/p7.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article 4: What is Life?</p>

                        </div>
                    </a>


                </div>
                <div class="col-sm- mr-0 mr-md-5 mb-4 mb-md-0">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                        <div class="">
                            <img src="{% static 'firsttune/p8.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article 5: What is Life?</p>


                        </div>
                    </a>


                </div>
            </div>
            <div class="row align-items-center justify-content-start justify-content-md-start my-2 
            pt-2 border_dark_ mb-4 mx-3 mx-sm-auto">
                <div class="col-sm- mb-4 mb-md-0 ">
                    <a href="{% url 'firsttune:post1' %}" class="customcolor">
                        <div class="">
                            <img src="{% static 'firsttune/p9.jfif' %}" class="img-fluid  ">
                            <p class="my-3">Article 6: What is Life?</p>

                        </div>
                    </a>


                </div>
            </div>


            {% endblock %}
        </div>
</body>

</html>